# Generated by Django 5.2.8 on 2026-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified_category',
            field=models.CharField(blank=True, choices=[('painting', 'Painting'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
