# Generated by Django 5.2.8 on 2026-01-19 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_verified_category_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified_category',
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_categories',
            field=models.CharField(blank=True, help_text='Comma-separated list of verified categories', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProviderCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(upload_to='certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('carpentry', 'Carpentry'), ('ac_repair', 'AC Repair')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='account.profile')),
            ],
            options={
                'unique_together': {('provider', 'category')},
            },
        ),
    ]
