# Generated by Django 5.2.8 on 2026-01-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text="User's phone number", max_length=15, null=True, unique=True),
        ),
    ]
