# Generated by Django 5.2.8 on 2026-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(blank=True, help_text='Email verification code or token', max_length=64, null=True),
        ),
    ]
